// GENERATED by tool/apply_household_profile.dart from
// household_profiles/zandri-renier.json — do not hand-edit; edit that
// profile and rerun the tool instead.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// This household's Firebase Android config. `main.dart` only points
/// Firestore at the local emulator in debug builds, so release builds (the
/// ones actually installed on phones) use this config directly. No
/// `storageBucket` — Cloud Storage isn't used (it requires the paid Blaze
/// plan; item photos were dropped instead, see item.dart). No iOS support
/// yet — see CLAUDE.md.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for $defaultTargetPlatform.',
        );
    }
  }

  static const android = FirebaseOptions(
    apiKey: 'AIzaSyAAQoGUtnpqoJS2u5WxGKSjZKOzojmXrXw',
    appId: '1:726684429457:android:e7d82ad22f6e53dec96330',
    messagingSenderId: '726684429457',
    projectId: 'household-app-c121a',
  );
}
