import 'dart:convert';
import 'dart:io';

/// Generates `lib/firebase_options.dart` and
/// `lib/core/constants/household_constants.dart` from a household profile
/// JSON file (see `household_profiles/_example.json` for the shape) — the
/// per-household values previously hand-edited directly in those two files.
///
/// Usage: `dart run tool/apply_household_profile.dart household_profiles/<id>.json`
///
/// Each household gets its own Firebase project (so their data is fully
/// isolated — see CLAUDE.md's "Sharing with other households" section) and
/// this script bakes their profile's config into the two generated files
/// before `flutter build apk` runs, so the CI build matrix can produce one
/// APK per household from the same codebase.
void main(List<String> args) {
  if (args.length != 1) {
    stderr.writeln(
      'Usage: dart run tool/apply_household_profile.dart <profile.json>',
    );
    exit(1);
  }

  final profileFile = File(args[0]);
  if (!profileFile.existsSync()) {
    stderr.writeln('Profile not found: ${args[0]}');
    exit(1);
  }

  final profile =
      jsonDecode(profileFile.readAsStringSync()) as Map<String, dynamic>;
  _writeFirebaseOptions(profile);
  _writeHouseholdConstants(profile);
  stdout.writeln('Applied household profile "${profile['id']}".');
}

/// Wraps [value] as a single-quoted Dart string literal, escaping
/// backslashes/quotes so profile values can't break the generated source.
String _dartString(Object? value) {
  final escaped = '$value'.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
  return "'$escaped'";
}

void _writeFirebaseOptions(Map<String, dynamic> profile) {
  final firebase = profile['firebase'] as Map<String, dynamic>;

  final content =
      '''
// GENERATED by tool/apply_household_profile.dart from
// household_profiles/${profile['id']}.json — do not hand-edit; edit that
// profile and rerun the tool instead.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// This household's Firebase Android config. `main.dart` only points
/// Firestore at the local emulator in debug builds, so release builds (the
/// ones actually installed on phones) use this config directly. No
/// `storageBucket` — Cloud Storage isn't used (it requires the paid Blaze
/// plan; item photos were dropped instead, see item.dart). No iOS support
/// yet — see CLAUDE.md.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('DefaultFirebaseOptions have not been configured for web.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for \$defaultTargetPlatform.',
        );
    }
  }

  static const android = FirebaseOptions(
    apiKey: ${_dartString(firebase['apiKey'])},
    appId: ${_dartString(firebase['appId'])},
    messagingSenderId: ${_dartString(firebase['messagingSenderId'])},
    projectId: ${_dartString(firebase['projectId'])},
  );
}
''';
  File('lib/firebase_options.dart').writeAsStringSync(content);
}

void _writeHouseholdConstants(Map<String, dynamic> profile) {
  final household = profile['household'] as Map<String, dynamic>;
  final members = household['members'] as List<dynamic>;

  final memberUidConsts = StringBuffer();
  final seedEntries = StringBuffer();
  for (var i = 0; i < members.length; i++) {
    final member = members[i] as Map<String, dynamic>;
    final constName = 'member${i + 1}Uid';
    memberUidConsts.writeln(
      'const $constName = ${_dartString(member['uid'])};',
    );
    seedEntries.writeln(
      '  (uid: $constName, displayName: ${_dartString(member['displayName'])}, '
      'colorTag: ${_dartString(member['colorTag'])}),',
    );
  }

  final content =
      '''
// GENERATED by tool/apply_household_profile.dart from
// household_profiles/${profile['id']}.json — do not hand-edit; edit that
// profile and rerun the tool instead.
//
// This app has exactly one household, and there's no auth to derive IDs
// from (decision #2 in CLAUDE.md — no auth at all, not even a PIN). So the
// household and member IDs are fixed constants rather than generated:
// every install of this household's build resolves to the same
// `/households/{defaultHouseholdId}` document and the same member docs,
// with no pairing/invite step needed for every member's phone to sync.
//
// [HouseholdRepository.ensureSeeded] creates these documents the first
// time any device on this household's Firebase project sees an empty
// database.
const defaultHouseholdId = ${_dartString(household['id'])};
const defaultHouseholdName = ${_dartString(household['name'])};

$memberUidConsts
const defaultMemberSeeds = [
$seedEntries];
''';
  File(
    'lib/core/constants/household_constants.dart',
  ).writeAsStringSync(content);
}
