// GENERATED by tool/apply_household_profile.dart from
// household_profiles/zandri-renier.json — do not hand-edit; edit that
// profile and rerun the tool instead.
//
// This app has exactly one household, and there's no auth to derive IDs
// from (decision #2 in CLAUDE.md — no auth at all, not even a PIN). So the
// household and member IDs are fixed constants rather than generated:
// every install of this household's build resolves to the same
// `/households/{defaultHouseholdId}` document and the same member docs,
// with no pairing/invite step needed for every member's phone to sync.
//
// [HouseholdRepository.ensureSeeded] creates these documents the first
// time any device on this household's Firebase project sees an empty
// database.
const defaultHouseholdId = 'default';
const defaultHouseholdName = 'Our Household';

const member1Uid = 'member-1';
const member2Uid = 'member-2';

const defaultMemberSeeds = [
  (uid: member1Uid, displayName: 'Zandri', colorTag: '#3A6351'),
  (uid: member2Uid, displayName: 'Renier', colorTag: '#8E5B3C'),
];
